spring:
  application:
    name: quiz_challenge_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #local??
    url: jdbc:mysql://localhost:3306/quiz_challenge?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    docker ??
    #    url: jdbc:mysql://mysql-container:3306/keyAppsk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root #local, docker
    password: 1234 #local. docker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect