spring:
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active: local
  application:
    name: quiz_challenge_backend
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.springframework.web.cors.DefaultCorsProcessor: TRACE
#서명 key로 사용할 임의의 문자 16byte
jwt:
  header: Authorization
  access_token_expiration_time: 60 #1시간
  refresh_token_expiration_time: 86400 #1일
  secret: SWyOuidP3cBXYp667MnXFOLZklTgfi6JufSq5Ptr6Elugp3VrZOuT5AYCyt2qZvklHxaAxuesGJg6BT35tge8p

#logging:
#  level:
#    root: debug

